---
- id: pipenv_check
  name: check for pipenv PyUp safety
  description: Checks for PyUp Safety security vulnerabilities and against PEP 508 markers
  entry: pipenv check
  language: system
  files: ^Pipfile\.lock$
  pass_filenames: false
- id: pipenv_verify
  name: verify if Pipfile.lock is up-to-date
  description: Verify the hash in Pipfile.lock is up-to-date
  entry: pipenv verify
  language: system
  files: ^Pipfile$
  pass_filenames: false
